Add test for get stored flows from flow_manager
amlight/kytos-end-to-end-tests pull request #192
Opened 2022-12-18 23:05 UTC by gretelliz

Fix #174 

 Add `test_e2e_40_sdntrace.py::TestE2ESDNTrace::test_030_run_sdntrace_for_stored_flows` to test how the traces are obtained from flow_manager stored_flow.

Also, `test_e2e_40_sdntrace.py::TestE2ESDNTrace::test_001_run_sdntrace_cp` hass passed.

2022-12-19 14:01 UTC, viniarck commented on tests/test_e2e_40_sdntrace.py
> +    def test_030_run_sdntrace_for_stored_flows(self):
This test case is relatively very similar to what `test_001_run_sdntrace_cp` covers. Maybe you could cover the `traces/` endpoint here instead to increase coverage? Covering with 2 or more traces the `traces/` endpoint would be great to have.

2022-12-19 14:02 UTC, viniarck commented on tests/test_e2e_40_sdntrace.py
> +    # @pytest.mark.xfail
@gretelliz, great to know that we can remove the xfail mark. But, let's delete the line, including the comment of the previous line that is obsolete.

2022-12-20 12:50 UTC, viniarck commented on kytos-init.sh
> +#python3 -m pytest $TESTS --reruns $RERUNS -r fEr
This was accidentally committed

2022-12-20 12:52 UTC, viniarck requested changes
Gretel, 

The test case for the bulk endpoint it'd be great to cover more than one trace, since that's the typically how the bulk endpoint will be used, can you adapt the test case?

Also there is accidental committed changes.

2022-12-24 02:17 UTC, gretelliz commented
@viniarck, note that now the `/traces` endpoint is tested for 4 traces, two of them are the same, so only 3 are returned. Two of them correspond to a same switch and the other to another switch.

2023-01-06 13:17 UTC, viniarck approved these changes
LGTM. It's great to have this coverage @gretelliz

2023-01-06 13:19 UTC, merged