Added test for validating the deletion of a maintenance window
amlight/kytos-end-to-end-tests pull request #2
Opened 2021-03-09 18:10 UTC by dgarc330

Added def test_011_delete_mw_on_switch(self) function

2021-03-09 21:29 UTC, ajoaoff requested changes

2021-03-09 21:29 UTC, ajoaoff commented on tests/test_e2e_15_maintenance.py
> +        response = requests.get(api_url, data=json.dumps(payload), headers={'Content-type': 'application/json'})["id"]
Here you should make a POST request, not a GET, to create the maintenance window.
```suggestion
        response = requests.post(api_url, data=json.dumps(payload), headers={'Content-type': 'application/json'})["id"]
```

2021-03-09 21:29 UTC, ajoaoff commented on tests/test_e2e_15_maintenance.py
> +                print("Maintenance window deleted correctly")
In a GET request you should not provide a payload.
You could also request for the specific maintenance window you are going to check, and see if the status is 404.
```suggestion
        req = requests.get(my_api_url)
        assert req.status_code == 404
```

2021-03-10 19:38 UTC, ajoaoff approved these changes

2021-03-10 22:02 UTC, dgarc330 commented on tests/test_e2e_15_maintenance.py
> +        response = requests.get(api_url, data=json.dumps(payload), headers={'Content-type': 'application/json'})["id"]
You are right Italo, that is leftover code. I will update the commit to remove that, thank you

2021-03-11 15:47 UTC, italovalcy requested changes
Daniela, here is my review requesting the changes

2021-03-11 15:47 UTC, italovalcy commented on tests/test_e2e_15_maintenance.py
> +        response = requests.post(api_url, data=json.dumps(payload), headers={'Content-type': 'application/json'})["id"]
The id should be removed from the end of the request.post call:

```suggestion
        response = requests.post(api_url, data=json.dumps(payload), headers={'Content-type': 'application/json'})
```

2021-03-11 16:28 UTC, italovalcy requested changes

2021-03-11 16:28 UTC, italovalcy commented on tests/test_e2e_15_maintenance.py
> +        payload = {
Even though a description is not mandatory for a MW, due to an issue (https://github.com/kytos/maintenance/issues/28) the test will not work if you dont provide the description

```suggestion
        payload = {
            "description":  "mw for test 1",
```

2021-03-11 16:28 UTC, italovalcy commented on tests/test_e2e_15_maintenance.py
> +        mw_id = json_data["id"]
the correct returned attribute is `mw_id` not `id`
```suggestion
        mw_id = json_data["mw_id"]
```

2021-03-11 16:28 UTC, italovalcy commented on tests/test_e2e_15_maintenance.py
> +        assert delete_response.status_code == 204
The return code is actually 200 not 204
```suggestion
        assert delete_response.status_code == 200
```

2021-03-11 16:28 UTC, italovalcy commented on tests/test_e2e_15_maintenance.py
> +        req = requests.get(my_api_url)
typo:
```suggestion
        req = requests.get(mw_api_url)
```

2021-04-19 20:26 UTC, closed without merging